import React from 'react';
import { ChevronDown, Bot, HelpCircle, MessageSquare } from 'lucide-react';

const FAQ = ({ onOpenChat }) => {
  const faqs = [
    {
      question: "When do these changes officially take effect?",
      answer: "The comprehensive tax reforms are scheduled for full implementation on January 1, 2026. This timeline allows for proper legislative passage, gazetting, and administrative transition for businesses and taxpayers."
    },
    {
      question: "Will the average citizen see a tax increase?",
      answer: "No. The primary goal of the 2024-2026 reform is consolidation, not an increase in the tax burden. Most Nigerians will maintain their current effective tax rates, while low-income earners may benefit from broader exemptions."
    },
    {
      question: "What specific protections are provided for Small Businesses?",
      answer: "Small businesses with an annual turnover of under ₦50 million are 100% exempt from corporate income tax. Additionally, the reforms aim to eliminate 'nuisance taxes' and multiple taxation that currently hinder SME growth."
    },
    {
      question: "How is VAT distribution being modernized?",
      answer: "The VAT rate remains at 7.5%. However, the distribution formula is shifting toward a 'Derivation-Based' model (60%), ensuring that VAT revenue generated by consumption in a state stays largely within that state's economy."
    },
    {
      question: "Is the FIRS being scrapped?",
      answer: "The Federal Inland Revenue Service (FIRS) is being renamed and restructured into the Nigeria Revenue Service (NRS). This is more than a name change; it is a structural modernization to make revenue collection more efficient and digitally driven."
    },
    {
      question: "How can I verify if my business is compliant with the new laws?",
      answer: "Business owners should review the 'Tax Administration Bill' PDF in our Resources section. You can also use our AI Assistant to upload your current tax scenario for a summarized impact analysis based on the new bills."
    }
  ];

  return (
    <section id="faq" className="py-20 md:py-28 bg-[#f8fafc] scroll-mt-20 relative">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Header Section */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 text-[#008751] font-bold uppercase tracking-[0.2em] text-[10px] mb-4">
            <HelpCircle className="w-4 h-4" />
            Tax Reform Knowledge Base
          </div>
          <h2 className="text-4xl md:text-5xl font-black text-gray-900 tracking-tight mb-4">
            Common <span className="text-[#008751]">Questions.</span>
          </h2>
          <p className="text-gray-500 font-medium text-sm md:text-base max-w-xl mx-auto">
            Everything you need to know about the transition to the 2026 Nigerian Tax System.
          </p>
        </div>
        
        {/* Accordion List */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <details 
              key={index} 
              className="group bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-all duration-300 overflow-hidden open:border-[#008751]/30 open:ring-1 open:ring-[#008751]/10"
            >
              <summary className="p-6 md:p-8 cursor-pointer flex items-center justify-between gap-4 list-none">
                <span className="font-bold text-gray-900 text-left flex-1 text-sm md:text-base pr-4">
                  {faq.question}
                </span>
                <div className="w-8 h-8 rounded-full bg-gray-50 flex items-center justify-center group-open:bg-[#008751] group-open:text-white transition-colors duration-300">
                  <ChevronDown className="w-5 h-5 group-open:rotate-180 transition-transform duration-300" />
                </div>
              </summary>
              <div className="px-6 md:px-8 pb-8 pt-0">
                <div className="h-[1px] w-full bg-gray-50 mb-6" />
                <p className="text-gray-600 leading-relaxed text-sm md:text-base font-medium opacity-90 border-l-4 border-[#A88948] pl-6">
                  {faq.answer}
                </p>
              </div>
            </details>
          ))}
        </div>
        
        {/* AI Support CTA Card */}
        <div className="mt-16 bg-[#004d2f] rounded-[2.5rem] p-8 md:p-12 text-center relative overflow-hidden shadow-2xl">
          {/* Subtle Decorative Circle */}
          <div className="absolute -bottom-10 -right-10 w-40 h-40 bg-white/5 rounded-full pointer-events-none" />
          
          <div className="relative z-10">
            <div className="w-16 h-16 bg-[#A88948] rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-xl">
              <Bot className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-2xl md:text-3xl font-black text-white mb-4 tracking-tight">
              Still have specific questions?
            </h3>
            <p className="text-green-100/70 mb-8 text-sm md:text-base max-w-md mx-auto font-medium">
              Our AI assistant is trained on the full text of the 2024 bills to provide you with precise, legal-backed information.
            </p>
            <button
              onClick={onOpenChat}
              className="bg-white text-[#004d2f] hover:bg-[#A88948] hover:text-white px-10 py-4 rounded-xl font-black transition-all text-xs uppercase tracking-widest flex items-center justify-center gap-3 mx-auto shadow-lg active:scale-95"
            >
              <MessageSquare className="w-4 h-4" />
              Start Consultation
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ;